# Generated by Django 2.1 on 2018-11-30 19:08

import Main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_customerdetails_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.CharField(max_length=250)),
                ('image', models.FileField(upload_to=Main.models.user_directory)),
            ],
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='image',
            field=models.FileField(upload_to=Main.models.user_directory),
        ),
    ]
