# Generated by Django 2.1 on 2018-11-30 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetails',
            name='image',
            field=models.FileField(default='none', upload_to='image/'),
            preserve_default=False,
        ),
    ]
